-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 12:44:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restruant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restruant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restruant` DEFAULT CHARACTER SET utf8 ;
USE `restruant` ;

-- -----------------------------------------------------
-- Table `restruant`.`reviewer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restruant`.`reviewer` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `restruant` VARCHAR(45) NULL,
  `review` VARCHAR(45) NULL,
  `datevisited` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
